name: Java CI/CD com Docker

on:
  push:
    branches: [ "main", "staging" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build com Maven
        run: mvn clean package -DskipTests
        working-directory: coletaDeResiduos

      - name: Build da imagem Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/coleta-de-residuos:${{ github.sha }} .
        working-directory: coletaDeResiduos

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push da imagem
        run: docker push ${{ secrets.DOCKER_USERNAME }}/coleta-de-residuos:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Exemplo de Deploy (personalize aqui)
        run: echo "Deploy para staging ou produção - personalize este step"


